# Generated by Django 6.0.5 on 2026-05-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('academic_title', models.CharField(max_length=200, verbose_name='Título académico')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('dedication', models.CharField(max_length=200, verbose_name='Dedicación Persona')),
                ('image', models.ImageField(upload_to='profile', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'person',
                'ordering': ['last_name'],
            },
        ),
    ]
