# Generated by Django 6.0.5 on 2026-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dedication',
            field=models.CharField(max_length=200, verbose_name='Dedicatoria'),
        ),
    ]
