# Generated by Django 6.0.5 on 2026-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_direction_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Titulo Academico'),
        ),
    ]
