# Generated by Django 6.0.5 on 2026-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
